# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: aws-iam
types:
    "aws-iam:index:Tags":
        type: object
        description: A map of tags to add.
        additionalProperties:
            type: string

resources:
    "aws-iam:index:AssumableRolesWithSAML":
        isComponent: true
        inputProperties:
            providerId:
                type: string
                description: ID of the SAML Provider. Use provider_ids to specify several IDs.
                default: ""

            providerIds:
                type: array
                description: List of SAML Provider IDs.
                items:
                    type: string

            awsSamlEndpoint:
                type: string
                description: AWS SAML Endpoint.
                default: https://signin.aws.amazon.com/saml

            adminRoleName:
                type: string
                description: IAM role with admin access.
                default: admin

            adminRolePath:
                type: string
                description: Path of admin IAM role.
                default: "/"

        requiredInputs: []
        properties:
        required:
            -
    "aws-iam:index:AssumableRole":
        isComponent: true
        inputProperties:
            trustedRoleActions:
                type: array
                description: Actions of STS.
                default: ["sts:AssumeRole"]
                items:
                    type: string

            trustedRoleArns:
                type: array
                description: ARNs of AWS entities who can assume these roles.
                default: []
                items:
                    type: string

            trustedRoleServices:
                type: array
                description: AWS Services that can assume these roles.
                default: []
                items:
                    type: string

            mfaAge:
                type: integer
                description: Max age of valid MFA (in seconds) for roles which require MFA.
                default: 86400

            maxSessionDuration:
                type: integer
                description: Maximum CLI/API session duration in seconds between 3600 and 43200.
                default: 3600

            createRole:
                type: boolean
                description: Whether to create a role.
                default: false

            createInstanceProfile:
                type: boolean
                description: Whether to create an instance profile.
                default: false

            roleName:
                type: string
                description: IAM role name.
                default: null

            rolePath:
                type: string
                description: Path of IAM role.
                default: "/"

            roleRequiresMfa:
                type: boolean
                description: Whether role requires MFA.
                default: true

            rolePermissionsBoundaryArn:
                type: string
                description: Permissions boundary ARN to use for IAM role.
                default: ""

            tags:
                $ref: "#/types/aws-iam:index:Tags"

            customRolePolicyArns:
                type: array
                description: List of ARNs of IAM policies to attach to IAM role.
                items:
                    type: string

            customRoleTrustPolicy:
                type: string
                description: A custom role trust policy.
                default: ""

            numberOfCustomRolePolicyArns:
                type: integer
                description: Number of IAM policies to attach to IAM role.
                default: null

            adminRolePolicyArn:
                type: string
                description: Policy ARN to use for admin role.
                default: "arn:aws:iam::aws:policy/AdministratorAccess"

            poweruserRolePolicyArn:
                type: string
                description: Policy ARN to use for poweruser role.
                default: "arn:aws:iam::aws:policy/PowerUserAccess"

            readonlyRolePolicyArn:
                type: string
                description: Policy ARN to use for readonly role.
                default: "arn:aws:iam::aws:policy/ReadOnlyAccess"

            attachAdminPolicy:
                type: boolean
                description: Whether to attach an admin policy to a role.
                default: false

            attachPoweruserPolicy:
                type: boolean
                description: Whether to attach a poweruser policy to a role.
                default: false

            attachReadonlyPolicy:
                type: boolean
                description: Whether to attach a readonly policy to a role.
                default: false

            forceDetachPolicies:
                type: boolean
                description: Whether policies should be detached from this role when destroying.
                default: false

            roleDescription:
                type: string
                description: IAM Role description.
                default: ""

            roleStsExternalId:
                type: array
                description: STS ExternalId condition values to use with a role (when MFA is not required).
                items:
                    type: string

        requiredInputs: []

        properties:
            iamRoleArn:
                type: string
                description: ARN of IAM role.

            iamRoleName:
                type: string
                description: Name of IAM role.

            iamRolePath:
                type: string
                description: Path of IAM role.

            iamRoleUniqueId:
                type: string
                description: Unique ID of IAM role.

            roleRequiresMfa:
                type: boolean
                description: Whether IAM role requires MFA.

            iamInstanceProfileArn:
                type: string
                description: ARN of IAM instance profile.

           iamInstanceProfileName:
                description: "Name of IAM instance profile"
                type: string

            iamInstanceProfileId:
                description: "IAM Instance profile's ID."
                type: string

            iamInstanceProfilePath:
                description: "Path of IAM instance profile."
                type: string

            roleStsExternalId:
                description: "STS ExternalId condition value to use with a role."
                type: string

        required:
            - iamRoleArn
            - iamRoleName
            - iamRolePath
            - iamRoleUniqueId
            - roleRequiresMfa
            - iamInstanceProfileArn
            - iamInstanceProfileName
            - iamInstanceProfileId
            - iamInstanceProfilePath
            - roleStsExternalId

    "aws-iam:index:AssumableRoleWithSAML":
        isComponent: true
        inputProperties:
            tags:
                $ref: "#/types/aws-iam:index:Tags"

            providerId:
                type: string
                description: ID of the SAML Provider. Use provider_ids to specify several IDs.
                default: ""

            providerIds:
                type: array
                description: List of SAML Provider IDs.
                items:
                    type: string

            awsSamlEndpoint:
                type: string
                description: AWS SAML Endpoint.
                default: https://signin.aws.amazon.com/saml

            roleName:
                type: string
                description: IAM role name.
                default: null

            roleNamePrefix:
                type: string
                description: IAM role name prefix.
                default: null

            roleDescription:
                type: string
                description: IAM Role description.
                default: ""

            rolePath:
                type: string
                description: Path of IAM role.
                default: "/"

            rolePermissionsBoundaryArn:
                type: string
                description: Permissions boundary ARN to use for IAM role.
                default: ""

            maxSessionDuration:
                type: integer
                description: Maximum CLI/API session duration in seconds between 3600 and 43200.
                default: 3600

            rolePolicyArns:
                type: array
                description: List of ARNs of IAM policies to attach to IAM role.
                items:
                    type: string

            numberOfRolePolicyArns:
                type: integer
                description: Number of IAM policies to attach to IAM role.
                default: null

            forceDetachPolicies:
                type: boolean
                description: Whether policies should be detached from this role when destroying.
                default: false

        requiredInputs: []

        properties:
            iamRoleArn:
                type: string
                description: ARN of IAM role.

            iamRoleName:
                type: string
                description: Name of IAM role.

            iamRolePath:
                type: string
                description: Path of IAM role.

            iamRoleUniqueId:
                type: string
                description: Unique ID of IAM role.

        required:
            - iamRoleArn
            - iamRoleName
            - iamRolePath
            - iamRoleUniqueId

    "aws-iam:index:AssumableRoleWithOIDC":
        isComponent: true
        inputProperties:
            tags:
                $ref: "#/types/aws-iam:index:Tags"

            providerUrl:
                type: string
                description: URL of the OIDC Provider. Use provider_urls to specify several URLs.
                default: ""

            providerUrls:
                type: array
                description: List of URLs of the OIDC Providers.
                items:
                    type: string

            awsAccountId:
                type: string
                description: The AWS account ID where the OIDC provider lives, leave empty to use the account for the AWS provider.
                default: ""

            roleName:
                type: string
                description: IAM role name.
                default: null

            roleNamePrefix:
                type: string
                description: IAM role name prefix.
                default: null

            roleDescription:
                type: string
                description: IAM Role description.
                default: ""

            rolePath:
                type: string
                description: Path of IAM role.
                default: "/"

            rolePermissionsBoundaryArn:
                type: string
                description: Permissions boundary ARN to use for IAM role.
                default: ""

            maxSessionDuration:
                type: integer
                description: Maximum CLI/API session duration in seconds between 3600 and 43200.
                default: 3600

            rolePolicyArns:
                type: array
                description: List of ARNs of IAM policies to attach to IAM role.
                items:
                    type: string

            numberOfRolePolicyArns:
                type: integer
                description: Number of IAM policies to attach to IAM role.
                default: null

            forceDetachPolicies:
                type: boolean
                description: Whether policies should be detached from this role when destroying.
                default: false

            oidcFullyQualifiedSubjects:
                type: array
                description: The fully qualified OIDC subjects to be added to the role policy.
                items:
                    type: string

            oidcSubjectsWithWildcards:
                type: array
                description: The OIDC subject using wildcards to be added to the role policy.
                items:
                    type: string

            oidcFullyQualifiedAudiences:
                type: array
                description: The audience to be added to the role policy. Set to sts.amazonaws.com for cross-account assumable role. Leave empty otherwise.
                items:
                    type: string

        requiredInputs: []

        properties:
            iamRoleArn:
                type: string
                description: ARN of IAM role.

            iamRoleName:
                type: string
                description: Name of IAM role.

            iamRolePath:
                type: string
                description: Path of IAM role.

            iamRoleUniqueId:
                type: string
                description: Unique ID of IAM role.

        required:
            - iamRoleArn
            - iamRoleName
            - iamRolePath
            - iamRoleUniqueId

    "aws-iam:index:Account":
        isComponent: true
        inputProperties:
            getCallerIdentity:
                type: boolean
                description: Whether to get AWS account ID, User ID, and ARN in which Pulumi is authorized.
                default: true

            accountAlias:
                type: string
                description: AWS IAM account alias for this account.

            createAccountPasswordPolicy:
                type: boolean
                description:  Whether to create AWS IAM account password policy.
                default: true

            maxPasswordAge:
                type: integer
                description: The number of days that an user password is valid.
                default: 0

            minimumPasswordLength:
                type: integer
                description: Minimum length to require for user passwords.
                default: 8

            allowUsersToChangePassword:
                type: boolean
                description: Whether to allow users to change their own password.
                default: true

            hardExpiry:
                type: boolean
                description: Whether users are prevented from setting a new password after their password has expired (i.e. require administrator reset).
                default: false

            passwordReusePrevention:
                type: boolean
                description: The number of previous passwords that users are prevented from reusing.
                default: null

            requireLowercaseCharacters:
                type: boolean
                description: Whether to require lowercase characters for user passwords.
                default: true

            requireUppercaseCharacters:
                type: boolean
                description: Whether to require uppercase characters for user passwords.
                default: true

            requireNumbers:
                type: boolean
                description: Whether to require numbers for user passwords.
                default: true

            requireSymbols:
                type: boolean
                description: Whether to require symbols for user passwords.
                default: true

        requiredInputs:
            - accountAlias

        properties:
            callerIdentityAccountId:
                description: "The AWS Account ID number of the account that owns or contains the calling entity"
                type: string

            callerIdentityArn:
                description: "The AWS ARN associated with the calling entity"
                type: string

            callerIdentityUserId:
                description: "The unique identifier of the calling entity"
                type: string

            iamAccountPasswordPolicyExpirePasswords:
                description: "Indicates whether passwords in the account expire. Returns true if max password age contains a value greater than 0. Returns false if it is 0 or not present."
                type: boolean

        required:
            - callerIdentityAccountId
            - callerIdentityArn
            - callerIdentityUserId
            - iamAccountPasswordPolicyExpirePasswords

    "aws-iam:index:Policy":
        isComponent: true
        inputProperties:
            name:
                type: string
                description: The name of the policy.

            path:
                type: string
                description: The path of the policy in IAM.
                default: "/"

            description:
                type: string
                description: The description of the policy.
                default: IAM Policy

            policyDocument:
                type: string
                description: The policy document.

            tags:
                $ref: "#/types/aws-iam:index:Tags"

        requiredInputs:
            - name
            - policyDocument

        properties:
            id:
                type: string
                description: The policy's ID.

            arn:
                type: string
                description: The ARN assigned by AWS to this policy.

            description:
                type: string
                description: The description of the policy.

            name:
                type: string
                description: The name of the policy.

            path:
                type: string
                description: The path of the policy in IAM.

            policyDocument:
                type: string
                description: The policy document.

        required:
            - id
            - arn
            - description
            - name
            - path
            - policyDocument

language:
    csharp:
        namespaces:
            "aws-iam": "AwsIam"
        packageReferences:
            Pulumi: 3.*
            Pulumi.Aws: 4.*
    go:
        generateResourceContainerTypes: true
        importBasePath: github.com/zchase/pulumi-aws-iam/sdk/go/aws-iam
    nodejs:
        dependencies:
            "@pulumi/aws": "^4.0.0"
        devDependencies:
            typescript: "^3.7.0"
    python:
        requires:
            pulumi: ">=3.0.0,<4.0.0"
            pulumi-aws: ">=4.0.0,<5.0.0"
