# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .account import *
from .assumable_role_with_oidc import *
from .assumable_role_with_saml import *
from .policy import *
from .provider import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-iam",
  "mod": "index",
  "fqn": "pulumi_aws_iam",
  "classes": {
   "aws-iam:index:Account": "Account",
   "aws-iam:index:AssumableRoleWithOIDC": "AssumableRoleWithOIDC",
   "aws-iam:index:AssumableRoleWithSAML": "AssumableRoleWithSAML",
   "aws-iam:index:Policy": "Policy"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-iam",
  "token": "pulumi:providers:aws-iam",
  "fqn": "pulumi_aws_iam",
  "class": "Provider"
 }
]
"""
)
